### ISSUE TITLE
unable to run http://localhost:29999/create?state=NoUsers with pact-jvm-server

### ISSUE THREAD

**Issue by anurag0249** [realestate-com-au/pact#102]
Hi ,

I am facing problem to execute an example on pact-jvm-server.
I have started pact-jvm server and its listening on port 29999 and GET call of " http://localhost:29999" giving JSON "{"ports": []}" in response.
I am using Postman for executing POST call http://localhost:29999/create?state=NoUsers
but I am not getting what will be perfect JSON for above post request.

**Comment by sergei-matheson** [comment]
Hi Anurag,
  That seems like an implementation-specific issue. You might be able to get specific help by opening an issue on the JVM Pact implementation page (https://github.com/DiUS/pact-jvm).
