### ISSUE TITLE
Pacts with webhooks

### ISSUE THREAD

**Issue by mikefarah** [realestate-com-au/pact#103]
We are using PACT goodness for testing our micro-service interactions, and one of our services uses webhooks to handle asynchronous, long running tasks.

Currently, the only way to PACTify this (as far as we know) is to have bi-directional pacts, one for the consumer to the provider for the original request, and one from the provider back to the consumer to the webhook callback.

This feels a littly iffy to me, I'd be happier with a single PACT file that goes along the lines of:

    animal_service.given("an alligator exists").
        upon_receiving("a request for an alligator").
        with(method: :get, path: '/alligator', query: 'callback=/alligator/response').
        will_respond_with(status: 200)
        will_callback_with(method: :post, path: '/alligator/response', body: {name: 'Betty'})
`

An immediate issue I can see (going from the example in the readme) is that the test is for the AnimalServiceClient wheras the callback would hit the controller of the consumer service.

Thoughts/Tips? Anyone done anything similar

**Comment by uglyog** [comment]
This may require a change to the specification (https://github.com/pact-foundation/pact-specification), so maybe raise an issue there.

My concern would be that this is a very specific use case, until you consider pacts with messages queues, in which case it would be more useful.

**Comment by mikefarah** [comment]
This has been moevd to https://github.com/pact-foundation/pact-specification/issues/26
