### ISSUE TITLE
Top level tear_down ignored unless set_up also present

### ISSUE THREAD

**Issue by duncan-bayne** [realestate-com-au/pact#111]
In the following code, `tear_down` is never executed:

```
Pact.provider_states_for 'Things' do
  # this never runs!
  tear_down do
    VCR.eject_cassette
    VCR.turn_off!
    PactProviderSetup::ElasticsearchIndex.delete_indices!
  end
  
  # provider states here ...
end
```

In order to have it execute, I need to add an empty `set_up` call at the top level:

```
Pact.provider_states_for 'Hotels' do
  set_up {}

  # this now runs!
  tear_down do
    VCR.eject_cassette
    VCR.turn_off!
    PactProviderSetup::ElasticsearchIndex.delete_indices!
  end

  # provider states here ...
end
```

Versions of things:

```
    pact (1.9.3)
      awesome_print (~> 1.1)
      json
      pact-mock_service (~> 0.8)
      pact-support (~> 0.5.7)
      rack-test (~> 0.6.2)
      randexp (~> 0.1.7)
      rspec (>= 2.14)
      term-ansicolor (~> 1.0)
      thor
      webrick

    ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

**Comment by bethesque** [comment]
Obviously crappy coding...

**Comment by bethesque** [comment]
Fixed. Funnily enough, there are a few lines of code in there (not the bug obviously :P) that I remember you helping with.

**Comment by bethesque** [comment]
Released 1.9.4.

**Comment by duncan-bayne** [comment]
Thanks for the quick fix! :smile:

Wow, that must have been years ago. Time flies. 

I've seen a couple of variations of this bug in various codebases recently, and have become a convert to @simonrussell's approach of (almost) always using `fetch` instead of `[]`. Makes me think a lot more carefully about default / nil cases. Maybe that says more about me than about the language :smile:

**Comment by bethesque** [comment]
Yeah, I like to use fetch in tests, because otherwise you risk getting nil == nil false positives.
