### ISSUE TITLE
Request Body matching does not remove array brackets from field name when converting request to hash for formdata.

### ISSUE THREAD

**Issue by gtg471h** [realestate-com-au/pact#112]
When setting up a provider state as:

```
 ... .with(method: :post,
        path: 'some_path',
        headers: { 'Content-Type' => 'application/x-www-form-urlencoded' },
        body: { key: [ "123", "456"] })
```

and passing the hash body:

```
{ key: [ "123", "456"] }
```

the comparison fails as the request body is deserialized as:

```
{ "key[]": [ "123", "456"] }
```

I believe this is due to the way the formdata is encoded by adding the "[]" to the end of the key but it not being removed again during parsing.

**Comment by bethesque** [comment]
Can you provide the failure output from the logs including the diff?

**Comment by bethesque** [comment]
Poke.

**Comment by SushmaShyam** [comment]
I am encountering the same issue. The failure output looks like this:

```
 Missing requests:
            	GET /questions?question_ids=1&question_ids=2

            Unexpected requests:
            	GET /questions?question_ids[]=1&question_ids[]=2
```
My expectation looks like this:

```

        some_service.given('some scenario')
          .upon_receiving('a request for questions')
          .with(method: :get, path: '/questions', query: {question_ids: [1,2]})
```

**Comment by bethesque** [comment]
Can you open this in the mock service project please? https://github.com/bethesque/pact-mock_service/issues

**Comment by bethesque** [comment]
Closing, moved to https://github.com/bethesque/pact-mock_service/issues/60
