### ISSUE TITLE
cucumber steps for pact?

### ISSUE THREAD

**Issue by blevonius-mdsol** [realestate-com-au/pact#113]
Hi,

Has anyone written cucumber steps for using pact on the consumer side? Not finding much out there.

CC: @kriogenx0 

Thanks.

**Comment by bethesque** [comment]
What @uglyog said on the mailing list. Cucumber is a BDD tool, where as Pact focuses on testing HTTP integrations. You'd be better off keeping those kind of tests separate, as they will be hard to debug and maintain. Pact is best used in the unit tests for the code that calls your HTTP service.
