### ISSUE TITLE
sharing provider states?

### ISSUE THREAD

**Issue by johngluckmdsol** [realestate-com-au/pact#114]
I'm guessing someone already thought of this, but I couldn't find any documentation on it.

Are there any plans to support Pact.provider_state_for <List> so that providers with multiple consumers can dry out provider states by asking their consumers to use something that already exists?

**Comment by johngluckmdsol** [comment]
I figured out how to do this

['some','values'].each do |consumer|
  Pact.provider_states_for consumer do

**Comment by bethesque** [comment]
There are global provider states. Use `Pact.provider_state`.
