### ISSUE TITLE
Configuration extension: Proposal for contact 

### ISSUE THREAD

**Issue by johngluckmdsol** [realestate-com-au/pact#116]
Since one things that Pact does is force the provider to talk to the consumer to resolve broken pacts, it makes sense to me that consumers should be able to provide some contact info.

Ideally, that information gets displayed in the broker, but it needs to be implemented in ConfigurationExtension first and then written to the pact. It would then be displayed on the main broker page.  This would be particularly helpful in large/distributed/siloed organizations where it is not always clear who owns particular pieces of code.

I'm happy to attempt to implement it on the Ruby side if folks think this is a good idea.  I'm thinking something basic initially, like an optional free form test field field.  I can resume this conversation in the dev forum if so desired

**Comment by bethesque** [comment]
That would be fantastic! Like so many things, something along these lines was discussed a while back, but it never got done. I was thinking it should go in the metadata, but then I realised that perhaps it belongs in the consumer/provider descriptions blocks. What do you think about something like this:

```ruby
Pact.consumer "Foo consumer" do

  supported_by "Foo Team on Level 3", with_email_address: "team@foo.com"

  has_pact_with "Foo provider" do
  end
end

```

```json
"consumer": {
    "name": "Foo consumer",
    "supportName": "Foo Team on Level 3",
    "supportEmailAddress": "team@foo.com"
  },
```

If we have an email field, then my long term vision for making the pact broker (or another service) be able to send build updates to the relevant people when things break will be easier.

Yes, please do post this to the dev mailing list so other people can hear about it.

**Comment by uglyog** [comment]
Also post it to the specification project so it can be tracked there: https://github.com/pact-foundation/pact-specification

**Comment by bethesque** [comment]
Any movement on this @johngluckmdsol? I think it's a great idea.

**Comment by johngluckmdsol** [comment]
Hey Beth, sorry, no.  I took a  a brief look at it but have since been busy
as the progress of our pact implementation has slowed.  I should know more
next week.  As soon as I'm ready to start, I'll join the developer group.
Unfortunately, I can't commit to building this feature at this time so if
you or someone else wants to work on it, please feel free to do so.

**Comment by bethesque** [comment]
Righto.

**Comment by bethesque** [comment]
Have moved this to pact-specification repo, closing here.
