### ISSUE TITLE
Gateway support?

### ISSUE THREAD

**Issue by johngluckmdsol** [realestate-com-au/pact#117]
Hey all,

As I'm implementing, I've discovered that our developers really want to support our gateway client.  While on the consumer side, I could easily implement the proxy, the provider implementation appears to really want a path, but if I were to implement this the way our code really does this, I would need to put an instantiation of the gateway client resource.   

This is not a [passthrough](https://github.com/realestate-com-au/pact/wiki/Why-Pact-may-not-be-the-best-tool-for-testing-pass-through-APIs) as you describe it because the gateway client will actually return the same thing service 

It appears that to do this the way the developers want me too, I'll have to monkey patch.  So the questions I have are:

1. Is this a good idea?  
2. If so, do you have any recommendations for how to do it (examples, is it on the roadmap and I'm just missing it?)
3. If it's not a good idea, can you help me out with some arguments to talk them out of it?

**Comment by uglyog** [comment]
Just to make it clear, does your consumer makes requests to an API gateway, which in turn, forwards the requests on to the provider? Or is the gateway translating the requests and responses in some way?

**Comment by johngluckmdsol** [comment]
Our gateway is a fork of Eureka(https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance).  I don't believe it does any translation, but I will confirm that.

**Comment by uglyog** [comment]
So the problem is that the path the client uses (and what gets persisted into the pact file) will be different to what the running provider responds to?

**Comment by johngluckmdsol** [comment]
The problem is that the client doesn't use a path, so there is no path to persist to the pact file. It simply gives its resource payload to the gateway and the gateway knows how to map the resource it got to 1. the service, 2. the correct endpoint. 

So I would have to write a module to override some of the behavior, which isn't that much of a problem but, since we know the gateway mapping works (the gateway has its own tests) and there isn't much point in testing via the client.  I suppose something could go wrong where, if I just used the path, I could specify an incorrect endpoint the operates as expected, but that seems unlikely.

I'm just wondering if you all have any recommendations

**Comment by ivan-kolmychek** [comment]
@johngluckmdsol 

Did you modify anything significantly in your Eureka fork?

Because if not, [this diagram](https://github.com/Netflix/eureka/raw/master/images/eureka_architecture.png
) says that you actually have three relationships/connections:
![eureka_architecture](https://cloud.githubusercontent.com/assets/5011577/19530731/bd00809c-963d-11e6-8fa8-62476a9ee973.png)

- Server app -> Eureka server (to register)
- Client app -> Eureka server (to request a data about any instance of server app registered and alive rigt now)
- Client app -> Server app (actual request)

Have you tried to inspect what requests your app does when you do `Client::Resource.('stuff here')` in your code?

**Comment by johngluckmdsol** [comment]
@ivan-kolmychek, I think I see what you are heading.  If I can get the endpoint from the client in advance, I can write it to the client.  It's a bit heavy on overhead because I'll have to stand up a local instance of the gateway server, but it just might work.  It's not a pure unit test though.

**Comment by ivan-kolmychek** [comment]
@johngluckmdsol you, you don't have to, as you can **fake responses to both requests** (to gateway and to service app) in your test.
You'll just have to make sure that second request is going to the path that was in your response from gateway.

I think that's probably something that you can test in isolation.

**Comment by johngluckmdsol** [comment]
@ivan-kolmychek What you suggested is how I've implemented it. Some of my developers thought there might be some value in getting the mappings from the gateway.  Given that the gateway will soon be optional, what I think I've come to the conclusion that there is no need to add the gateway to these tests.  Thanks for the input

**Comment by ivan-kolmychek** [comment]
@johngluckmdsol I'm not sure that's even a gateway, sounds more like a coordinator to me, as requests from client to server still have to be made directly. But maybe I misunderstand that.

(Disclaimer: I'm putting this info here just in case someone will be looking for stuff like this. I'm glad that you've solved your issue, so this may be a bit irrelevant to your case.)

In one of the projects I worked with, we had a gateway service which presented "public API" endpoints to world and did calls to internal APIs. We tested it with pact from two sides:
- As a client for internal API's in public API tests - to make sure we have contracts between gateway as a client and number of services providing internal APIs
- As a provider for our reference implementation of client for public API - to make sure we have contract with sample client and we don't break the expectations of public API

In your case, even if the client is depending on coordinator service data not all the time but **in some cases**, I think you may use pact to get contract with gateway **in those cases**, if you think those are important and should be tested. Still, tests, in my opinion, should bring value to you and your project, not be a burden, so if you think that it doesn't really need tests - so be it. :) 

Also, without verification pact is just a description of how you expect service to behave, and verifying the pacts conformance on coordinators side is yet another topic.
