### ISSUE TITLE
Verifying pacts for non-Rack apps

### ISSUE THREAD

**Issue by villins** [realestate-com-au/pact#131]
Can not use config.ru run app When verifying pacts for non-Rack apps?

**Comment by bethesque** [comment]
If it's a ruby app, you could write an adapter (I can show you how to do this) or you can use pact-provider-proxy https://github.com/bethesque/pact-provider-proxy

**Comment by villins** [comment]
@bethesque i use pact-provider-proxy for  non-Rack apps, but it can not work for me, find config.ru run app by default.
I remove config.ru file, it will throw error with not found config.ru

**Comment by bethesque** [comment]
Can you create a repository with your code so I can try and work out what is going wrong?

**Comment by villins** [comment]
@bethesque ok, https://github.com/villins/pact_example

**Comment by bethesque** [comment]
So are you starting the provider manually before you run the test?

**Comment by bethesque** [comment]
You need to delete the following code:

```
Pact.service_provider "example service" do

  honours_pact_with 'example service' do
    pact_uri ''
  end

end
```

This is used when you are verifying a rack app.

**Comment by bethesque** [comment]
Just wanted to check, because I'm not sure if you were just using the Sinatra app as a temporary example - you do know that Sinatra apps are rack apps? I've forked the code to show you how to test a sinatra app

https://github.com/bethesque/pact_example

Sorry if you do know this already!

**Comment by villins** [comment]
@bethesque i know  Sinatra app is rack apps. But how to test non-rack app just like Node.js app or others. Rack app can pass testing while i block in non-rack app test.
Sorry.  My code make u confused.

**Comment by bethesque** [comment]
No worries! Deleting the `Pact.service_provider ` block will fix your problem. There are other implementations for verifying pacts for different technology stacks. See the list under "Implementations" here: https://docs.pact.io/
