### ISSUE TITLE
PACT Dsl closeObject not working as advertised

### ISSUE THREAD

**Issue by pamelawilson65** [realestate-com-au/pact#134]
Either I didn't understand the example of how to use closeObject() or it's not working as expected.  In the code attached, as you can see there are syntax errors in the usage.  This is how it's shown in the example from this page https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit, in the matching any key section. 
![pactdslsyntaxerror](https://cloud.githubusercontent.com/assets/25983585/25050921/03fb0c96-2118-11e7-8429-7b02e3ecc8fc.jpg)

**Comment by bethesque** [comment]
Hi @pamelawilson65, can you ask this on stackexchange and tag it with pact-java please? This is the repository for the ruby implementation.

**Comment by pamelawilson65** [comment]
Beth hi, we are working with PACT-JVM and have a java implementation. The code snippet I provided is in a JUnit test, for PACT file generation.  Does stackoverflow deal with PACT DSL language issues?  I thought since this was PACT DSL specific issue, this forum would be the best place to ask the question.

**Comment by bethesque** [comment]
Hi @pamelawilson65, yes, stackoverflow deals with DSL issues for all the implementations - you just need to tag it with pact-jvm so the Pact JVM supporters will see it. I can't help you with Junit and JVM questions, as I only work on the ruby implementation.

**Comment by pamelawilson65** [comment]
OK @bethesque, thank you so much for your guidance, I will do as you suggested. THANKS!
