### ISSUE TITLE
Pact json file is not being parsed correctly into Rails API during verify

### ISSUE THREAD

**Issue by mohjay** [realestate-com-au/pact#136]
Hi Beth,

Noticed some strange behaviour when using PACT. Given I have the following interaction:

`{
     "description": "a request to update a user, containing user object",
      "provider_state": "user exists in database",
      "request": {
        "method": "patch",
        "path": "/api/v1/users/2",
        "headers": {
          "Accept": "application/json"
        },
        "body": {
          "user": {
            "email": "admin1@gmail.au"
          }
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        }
      }
    }`

When I run `be rake pact:verify` I get an error because the body parameter is not being parsed correctly. I'm not sure if this is a user error or a problem with PACT.

Inspecting the params in the update action in the users controller gives me this:

`<ActionController::Parameters {"{\"user\":{\"email\":\"admin1@gmail.au\"}}"=>nil, "controller"=>"api/v1/users", "action"=>"update", "id"=>"2"} permitted: false>`

It breaks because the `{"{\"user\":{\"email\":\"admin1@gmail.au\"}}"=>nil` should be `"user" => {"email" => "admin1@gmail.au"}`

Any help would be much appreciated.

Using v1.10.0 of PACT.

Cheers,
Mo

**Comment by bethesque** [comment]
I reckon your request needs a content type of "application/json".

**Comment by mohjay** [comment]
Thanks, you're a legend.
