### ISSUE TITLE
write contract to test restful with json base on junit

### ISSUE THREAD

**Issue by hanbin** [realestate-com-au/pact#147]
write contract to test restful interface with json base on junit, there's any document or demo?

**Comment by bethesque** [comment]
https://docs.pact.io/

**Comment by hanbin** [comment]
@bethesque I mean i want to write contract file directly, but i do not know how to do.
and https://docs.pact.io had review

**Comment by uglyog** [comment]
If you want to use junit, please refer to https://github.com/DiUS/pact-jvm

**Comment by bethesque** [comment]
@hanbin you don't write the contract directly. It is an artefact generated by running tests with the pact mock service.

**Comment by hanbin** [comment]
@bethesque  but i only want to test my interface with contract file and junit.

**Comment by bethesque** [comment]
That is not the way pact is designed. It will be difficult. If you are not going to use Pact for its actual purpose (contract testing using consumer driven contracts) then I would recommend you use another tool that is more suited to your use case.

If you really want to hand code contract files, you can read the pact specification. https://github.com/pact-foundation/pact-specification/ Please remember that Pact is a contract testing tool, not a tool for functional testing. https://docs.pact.io/best_practices/contract_tests_not_functional_tests.html

**Comment by hanbin** [comment]
@bethesque thanks.
