### ISSUE TITLE
pactSpecification v3 plan?

### ISSUE THREAD

**Issue by bootstraponline** [realestate-com-au/pact#150]
It looks like [pact-jvm](https://github.com/DiUS/pact-jvm#supported-jdk-and-specification-versions) is the only pact implementation with v3 support currently. Is there a plan to update Pact Ruby to support v3?

**Comment by bethesque** [comment]
There is, but we'll actually be using a different implementation under the hood, so it won't actually be the Ruby code that is updated. Please read the last paragraph of the History for an explanation of what the plan is for the future. https://docs.pact.io/about_pact/history.html

It is currently being worked on, but I wouldn't imagine it will be out for quite a few months yet.

**Comment by afriqs** [comment]
Hi,

Could we have an update on the status of this *migration* ? Is there an alternative to this gem or a tutorial to use the **Rust** implementation ?
