### ISSUE TITLE
Escape markdown chars in pacticipant names in markdown renderer

### ISSUE THREAD

**Issue by bethesque** [realestate-com-au/pact#45]
eg.

**Comment by bethesque** [comment]
Done in https://github.com/realestate-com-au/pact/commit/dbf26f2d3100c88c033d581683e0e05dbe6dfe2c, to be released in > 1.8.1.

**Comment by alext** [comment]
I think this also needs to be applied to the `InteractionRenderer`. At the moment, a provider_state description with more than one `_` in it will result in parts of it being italicised. Reading the code, this will probably happen for the interaction description as well.

**Comment by bethesque** [comment]
Good point. Fixed in https://github.com/realestate-com-au/pact/commit/5f76726.

**Comment by alext** [comment]
Thanks for that.

**Comment by tancnle** [comment]
Closed as per 5f76726?

**Comment by bethesque** [comment]
Yes, thanks.
