### ISSUE TITLE
Duplicate detection failing with SomethingLike

### ISSUE THREAD

**Issue by allavena** [realestate-com-au/pact#65]
I mentioned on the mailing list that setting up an identical second interaction was being rejected when it contained a Pact::SomethingLike, but not when it contained a Pact::Term.

This is the track the issue. 

I have not yet reproduced it on a small example, however, I have just noticed that in the json pact file, the Pact::SomethingLike is serialised to "amount": "#<Pact::SomethingLike:0x00000002b10d58>"
whereas the Pact::Term is correctly serialised to 
                "myobject": {
                  "json_class": "Pact::Term",
                  "data": {
                    "generate": "123",
                    "matcher": {
                      "json_class": "Regexp",
                      "o": 0,
                      "s": "\\d+"
                    }
                  }
                },

In my existing case, this is in the response body, a few level down in a hash, along the lines of:
body: {
  data: { 
    embeded_data: { 
      name: Pact::Term(...)
    }
 }
  info: { 
    amount: Pact::SomethingLike("20.00") 
 }
}

Maybe something is going wrong with a serialisation of Pact::SomethingLike when it's embedded a few level down in a hash.

**Comment by bethesque** [comment]
Very strange. I haven't been able to replicate this yet. The SomethingLike should be able to be embedded without problems, so something is definitely out there. Do you have active support JSON loaded? The tests run with and without active support JSON, to make sure that it behaves the same way each time (AS effs up the serialisation of things) but maybe a corner case slipped through.

**Comment by bethesque** [comment]
Any progress on this? I'd like to close it if it can't be reproduced.

**Comment by allavena** [comment]
Close as invalid.


I just had another look at it.  Somebody on my side was using

info: { amount: "#{Pact::SomethingLike.new(10)}"}


It shouldn't be embedded in a string but used directly: { amount:
Pact::SomethingLike.new(10) }


Tests do pass in the first case, which is why I didn't catch it earlier.
Everything is good when using the Pact::SomethingLike directly.

Thanks
André




Beth Skurrie wrote on 20/02/15 15:02:
>
> Any progress on this? I'd like to close it if it can't be reproduced.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realestate-com-au/pact/issues/65#issuecomment-75190084>.
>


-- 
André Allavena, PhD
CTO
Interactive Gaming Entertainment Pty Ltd

Suite 22, 20 Park Rd 
Milton Qld 4064
