### ISSUE TITLE
Will pact connect to some server via http when running the provider pact tests?

### ISSUE THREAD

**Issue by freewind** [realestate-com-au/pact#67]
I see in pact-jvm, when running the provider pact tests, it needs a server started, and pact will send http request to that server.

But I can't find similar logic for this ruby pact, and in some ruby projects that using pact, I didn't see any http server started neither.

How is ruby pact running the pact test on provider side?

**Comment by bethesque** [comment]
The Ruby pact verification uses Rack::Test. Pretty much every Ruby web
framework is built on Rack. No separate server process is required for
testing, it just uses the Rack interface to send mock HTTP requests to the
application.

See http://rack.github.io/ and https://github.com/brynary/rack-test for
more info.

**Comment by freewind** [comment]
@bethesque Thanks, I'm clear now
