### ISSUE TITLE
Pact Mock Service version number CLI

### ISSUE THREAD

**Issue by mboudreau** [realestate-com-au/pact#68]
I'm trying to get every developer on the same page, and that's not exactly easy when you don't know what version of pact that they're running locally.

This is why I'd like to create a quick plugin that checks to see if they're using the correct pact version when building/developing, but there doesn't seem to be a way to get the version number from the command line.

This, I imagine, would be a very simple feature that can add a lot of benefit for us and others.  If I have time, I might implement it myself (first foray into ruby!).

**Comment by bethesque** [comment]
Luckily, this is a solved problem! The way to get every developer using the same version of the mock service is to create a Gemfile for your project, specify the version of the mock server you want to use, and run the mock service using `bundle exec pact-mock-service`. Both the Gemfile and Gemfile.lock should be checked into the project. There will be no need to ask the service what version it is - you will know already.
