### ISSUE TITLE
Shall we add check that all the providerState are unique when generating the pact json file for consumers?

### ISSUE THREAD

**Issue by freewind** [realestate-com-au/pact#69]
From our discussion, I know that for each test case, the `providerState` can be none or unique. But there is no validation when generating the pact JSON file.

When we write tests, we may write them into several different files, and pact server will combine them together, so it's easily to write two tests with the same provider, but hard to find that.

You can see there are several test files there, and some test cases have the same providerState `listing-services with good bookmark-sync functionality`:

https://git.realestate.com.au/resi/saved-properties-dashboard/tree/master/test/pact

When the generated JSON file is uploaded to server, it may not easy to know there are duplicated provider state, since the file is usually big.

So I think is it possible to add the checking when generating?

**Comment by freewind** [comment]
Just confirmed from @bethesque, the state doesn't need to be unique

**Comment by bethesque** [comment]
Correct. The mock server will validate that the combination of description and provider state is unique though.
