### ISSUE TITLE
RuntimeError: Could not find provider state

### ISSUE THREAD

**Issue by anthonygreen** [realestate-com-au/pact#82]
Using PACT to test a node service I get the error

    An error occurred in an after hook
      RuntimeError: Could not find provider state "the service is running" for consumer Client

The PACT file is

    {
      "consumer": {
        "name": "Client"
      },
      "provider": {
        "name": "Service"
      },
      "interactions": [
        {
          "description": "a request for the index",
          "provider_state": "the service is running",
          "request": {
            "method": "get",
            "path": "/index.js"
          },
          "response": {
            "status": 200,
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ],
      "metadata": {
        "pactSpecificationVersion": "1.0.0"
      }
    }

**Comment by bethesque** [comment]
Have you defined your provider states? Please see the provider states documentation on the wiki.

**Comment by bethesque** [comment]
PS. Please use the pact-support mailing list for user issues, and keep Github issues for bugs. Closing.
