### ISSUE TITLE
Extending a Pact

### ISSUE THREAD

**Issue by egoodberry** [realestate-com-au/pact#84]
We're using pact to allow our mobile app development team to define their expectations of our API; they're creating JSON-based pacts via the Swift consumer library. The problem is that our API uses token-based authentication, which works off of request headers (which are fixed in the JSON files).

Would it be possible to extend a pact programmatically so as to allow for more realistic end-to-end testing (without stubbing out the backend)? I would imagine the API would look something like so:

```
Pact.provider_states_for "iOS" do
  set_up do |provider_state|
    provider_state.request.headers["Authentication"] = "foo"
  end
end
```

**Comment by bethesque** [comment]
It's something we've thought about, but have always managed to find a way to work around. I'm a little hesitant to add it, but can see why it would be useful.

How are you verifying the provider at the moment? Using pact-provider-proxy to verify against a running server, or running it against a normal Rack app?

**Comment by egoodberry** [comment]
We're running against a normal Rack app.

**Comment by bethesque** [comment]
In that case, you can do a quick and dirty trick using some Rack middleware.

```ruby
class ProxyRackApp
  def initialize app
    @app = app
  end

  def call env
    # Modify headers here!
    @app.call(env)
  end
end
```

```ruby
Pact.service_provider "My provider" do
  app { ProxyRackApp.new(your_provider_app) }
end
```

**Comment by bethesque** [comment]
Closing, assuming this helped.
