### ISSUE TITLE
Update wiki page on regular expressions and type matching w.r.t. spec v2 release

### ISSUE THREAD

**Issue by timoreimann** [realestate-com-au/pact#90]
The wiki page https://github.com/realestate-com-au/pact/wiki/Regular-expressions-and-type-matching-with-Pact still contains a few spots claiming that features only exist for the Ruby implementation of Pact until Pact specification version 2 has been released.

Now that the latter has happened, the obsolete wiki page references should be removed/updated.

**Comment by bethesque** [comment]
Good point, I've deleted those references.
