### ISSUE TITLE
Setting rspec before/after hooks around the :pact tag

### ISSUE THREAD

**Issue by sebglazebrook** [realestate-com-au/pact#91]
Hey @bethesque how's things? Long time no see!

I'm at Redbubble now and we just started to look at using Pact here.

When setting it up I've seen some funky things. Normally we use WebMock to mock out http requests, but obviously need to disable this when we are running pact tests.

In our rspec context we had before and after hooks disabling Webmock but when we tried to move these to `spec_helper.rb` it didn't work.

We thought we could do:

```
RSpec.configure do |config|
  config.before(:context, :pact) { WebMock.allow_net_connect! }
  config.after(:context, :pact) { WebMock.disable_net_connect! }
end

context "test something with pact", :pact do

  it "works" do
    subject
  end

end
```
But our before and after hooks never get run.

What we've had to do to get it to work is create a new tag and then have the tag on it's own context/describe.

```
RSpec.configure do |config|
  config.before(:context, :before_pact) { WebMock.allow_net_connect! }
  config.after(:context, :after_pact) { WebMock.disable_net_connect! }
end


describe "something here", :before_pact, :after_pact do
  context "test something with pact", :pact do

    it "works" do
      subject
    end
  end
end
```

Does that make sense?

Is this by design?

**Comment by sebglazebrook** [comment]
Adding @Catharz

**Comment by bethesque** [comment]
Hey seb! I wouldn't have thought the before and after context hooks had anything to do with pact itself. Can you get that pattern working with another arbitrary tag?

**Comment by Catharz** [comment]
Hi @bethesque, pairing with @sebglazebrook on this.

Thing we've just noticed is using the :pact tag with another tag on the same spec (or context) is only an issue if the other tag(s) have before, after or around hooks associated with them.

We'll work on a gist that demonstrates the problem.

**Comment by bethesque** [comment]
I'd be popping some pry statements in the hooks to see what order they're running in. Here's the relevant code:

https://github.com/realestate-com-au/pact/blob/master/lib/pact/consumer/rspec.rb
https://github.com/realestate-com-au/pact/blob/master/lib/pact/consumer/spec_hooks.rb

**Comment by sebglazebrook** [comment]
@bethesque @Catharz 
Was able to work this one out.
It's a couple of things: 

- If we want our rspec before/after hooks before pacts before/after hooks we have to require pact last:
e.g. Do this:
```
RSpec.configure do |config|
  config.before(:context, :pact) { WebMock.allow_net_connect! }
end

require_relative 'service_providers/pact_helper.rb'
```
Not this:
```
require_relative 'service_providers/pact_helper.rb'

RSpec.configure do |config|
  config.before(:context, :pact) { WebMock.allow_net_connect! }
end
```

Also we wanted to add an after hook to `WebMock.disable_net_connect!` so our non-pact test still alert us if they try to hit an endpoint but doesn't  look like that will work as pact write's it's pact file in an rspec "after suite" hook using a url `localhost:1234/pact` which get's picked up by WebMock as a http request.

To solve this we can either just disallow non localhost requests:

`WebMock.disable_net_connect!(:allow_localhost => true)`

or if we really want to be vigilant only allow pact's `write_pact` url through

`WebMock.disable_net_connect!(allow: /^http://localhost:(\d{2,4})\/pact$/)`

**Comment by bethesque** [comment]
Ok, good to know!
