### ISSUE TITLE
invalid option: --pact-helper

### ISSUE THREAD

**Issue by mszenher** [realestate-com-au/pact#93]
When I run `rake pact:verify`, the following command is generated:

```
SPEC_OPTS='' /Users/mszenher/.rvm/rubies/ruby-2.1.2/bin/ruby -S pact verify --pact-helper /Users/mszenher/Documents/work/plinth/spec/service_consumers/pact_helper.rb
```

Everything runs successfully (i.e. pacts are verified as expected) but at the end of the output I see:

```
invalid option: --pact-helper

Please use --help for a listing of valid options
```

This is actually breaking my pact CI b/c the invalid option raises an exception.

**Comment by bethesque** [comment]
What versions of pact and pact-support are you using? Are you using "bundle exec" to ensure you're getting the right versions?

**Comment by mszenher** [comment]
Hi Beth,

Thanks for getting back so quickly.  Using pact 1.9.0 and pact-support
0.5.4.  I am using "bundle exec", yes.

-Matt

**Comment by bethesque** [comment]
Hm, very strange. I can see the option in there. https://github.com/realestate-com-au/pact/blob/master/lib/pact/cli.rb#L8

What do you get if you run `SPEC_OPTS='' /Users/mszenher/.rvm/rubies/ruby-2.1.2/bin/ruby -S pact verify --help` ?

**Comment by mszenher** [comment]
I get ```No value provided for required options '--pact-helper'```

**Comment by bethesque** [comment]
Hahahah! There's just no pleasing it! I'll try and replicate.

**Comment by bethesque** [comment]
Ok, so I'm using the animal-service in the pact repo to test with. I deleted the path for the pact gem in the animal-service Gemfile so that it installed pact 1.9.0, and pact support 0.5.4. Also had to do a bundle update because some of the gems didn't work in ruby 2.2.2.

```
animal-service $ bundle list
Gems included by the bundle:
...
  * pact (1.9.0)
  * pact-mock_service (0.8.0)
  * pact-support (0.5.4)
...
```

Had to change the content type in `example/animal-service/lib/animal_service/api.rb` from `content_type :json` to `content_type "application/json;charset=utf-8"`, to make it pass.

```
$ bundle exec rake pact:verify
SPEC_OPTS='' /usr/local/var/rbenv/versions/2.2.2/bin/ruby -S pact verify --pact-helper /Users/beth/workspace/pact/example/animal-service/spec/service_consumers/pact_helper.rb
Reading pact at ../zoo-app/spec/pacts/zoo_app-animal_service.json

Verifying a pact between Zoo App and Animal Service
  Given there is an alligator named Mary
    a request for an alligator
      with GET /alligators/Mary
        returns a response which
          has status code 200
          has a matching body
          includes headers
            "Content-Type" with value "application/json;charset=utf-8"
  Given there is not an alligator named Mary
    a request for an alligator
      with GET /alligators/Mary
        returns a response which
          has status code 404
  Given an error occurs retrieving an alligator
    a request for an alligator
      with GET /alligators/Mary
        returns a response which
          has status code 500
          has a matching body
          includes headers
            "Content-Type" with value "application/json;charset=utf-8"

3 interactions, 0 failures
```

So, end result is I can't replicate it with this code. Can you make a repo with all the files necessary to replicate?

**Comment by mszenher** [comment]
Thanks!

**Comment by mszenher** [comment]
Weird!  I'll try to come up with steps to replicate on my side.

_Matt
